-- Replace service_templates with simplified services table and configure RLS

-- 1. Drop unused service_templates table
DROP TABLE IF EXISTS public.service_templates CASCADE;

-- 2. Create simplified services table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    icon VARCHAR(64) DEFAULT '🛠️',
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. Enable Row Level Security
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- 4. Add read-only policy for anon and authenticated users
CREATE POLICY "Allow public read access to active services"
ON public.services
FOR SELECT
TO anon, authenticated
USING (is_active = true);
