-- Replace service_templates with simplified services table and configure RLS

-- 1. Drop unused service_templates table
DROP TABLE IF EXISTS public.service_templates CASCADE;

-- 2. Create simplified services table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    icon VARCHAR(64) DEFAULT '🛠️',
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. Enable Row Level Security
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- 4. Add read-only policy for anon and authenticated users
CREATE POLICY "Allow public read access to active services"
ON public.services
FOR SELECT
TO anon, authenticated
USING (is_active = true);

-- 5. Seed initial list of available campus services
INSERT INTO public.services (name, description, icon, sort_order) VALUES
('Tutoring & Academic Help', 'Course tutoring, exam preparation, language lessons, assignment review', '📚', 1),
('Tech & Device Repair', 'Laptop repair, phone screen replacement, software troubleshooting', '💻', 2),
('Moving & Hauling Assistance', 'Help moving into dorms/apartments, heavy lifting, truck assistance', '📦', 3),
('Graphic Design & Creative', 'Posters, flyers, logos, social media graphics, UI/UX', '🎨', 4),
('Photography & Videography', 'Graduation photos, event coverage, portraits, video editing', '📸', 5),
('Cleaning & Organization', 'Dorm room cleaning, deep cleaning, room organizing', '🧹', 6),
('Music & Audio Services', 'DJing events, music lessons, audio editing/mixing', '🎵', 7),
('Hair, Beauty & Grooming', 'Haircuts, styling, braiding, makeup, nails', '✂️', 8),
('Delivery & Errand Running', 'Campus deliveries, grocery runs, package pick-ups', '🚴', 9),
('Fitness & Personal Training', 'Workout coaching, gym buddy, sports training', '💪', 10)
ON CONFLICT DO NOTHING;
